apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "redis.name" . }}
  namespace: {{ .Release.Namespace }}
data:
  redis-stack.conf: |
    {{- if .Values.redis.password }}
    requirepass {{ .Values.redis.password }}
    {{- end }}
    {{- if .Values.redis.persistence.enabled }}
    dir /data
    appendonly yes
    appendfsync everysec
    auto-aof-rewrite-percentage 100
    auto-aof-rewrite-min-size 64mb
    {{- end }}
    {{- if .Values.redis.extraConfig -}}
    {{- .Values.redis.extraConfig | nindent 4 }}
    {{- end }}
